import '../../style/modern-ui.css';
import { html } from './HtmlTag';
import { TypedEmitter } from '../../common/TypedEmitter';

interface QuickConnectEvents {
    connect: { name: string; host: string; port: number };
}

export class QuickConnect extends TypedEmitter<QuickConnectEvents> {
    private static instance?: QuickConnect;
    private container: HTMLElement;
    private isOpen = false;

    public static getInstance(): QuickConnect {
        if (!this.instance) {
            this.instance = new QuickConnect();
        }
        return this.instance;
    }

    private constructor() {
        super();
        this.container = document.createElement('div');
        this.render();
    }


    private async connectToDevice(device: { name: string; host: string; port: number }): Promise<void> {
        // Emit the connect event for listeners
        this.emit('connect', device);
        
        // Don't show success message here - wait for backend confirmation
        // Don't close the panel yet - wait for backend response
    }

    private render(): void {
        const content = html`
            <div class="quick-connect-panel ${this.isOpen ? 'fade-in' : ''}" style="display: ${this.isOpen ? 'block' : 'none'}">
                <div class="quick-connect-header">
                    <h2 class="quick-connect-title">
                        <svg viewBox="0 0 24 24" fill="currentColor">
                            <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z"/>
                        </svg>
                        快速连接
                    </h2>
                    <button class="btn btn-icon btn-secondary" onclick="QuickConnect.getInstance().close()">
                        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                            <path d="M6 18L18 6M6 6l12 12"/>
                        </svg>
                    </button>
                </div>
                
                <form class="quick-connect-form" onsubmit="return false;">
                    <div class="form-group">
                        <label class="form-label" for="device-host">主机/IP地址</label>
                        <input 
                            type="text" 
                            id="device-host" 
                            class="form-input" 
                            placeholder="192.168.1.100 或 localhost"
                            required
                        />
                    </div>
                    
                    <div class="form-group">
                        <label class="form-label" for="device-port">端口</label>
                        <input 
                            type="number" 
                            id="device-port" 
                            class="form-input" 
                            placeholder="5555"
                            value="5555"
                            min="1"
                            max="65535"
                            required
                        />
                    </div>
                    
                    <button type="submit" class="btn btn-primary" style="width: 100%" onclick="QuickConnect.getInstance().handleConnect()">
                        连接
                    </button>
                </form>
                
            </div>
        `;

        this.container.innerHTML = '';
        this.container.appendChild(content.content.firstElementChild as HTMLElement);
    }

    public open(): void {
        this.isOpen = true;
        this.render();
    }

    public close(): void {
        this.isOpen = false;
        this.render();
    }

    public toggle(): void {
        this.isOpen = !this.isOpen;
        this.render();
    }

    public handleConnect(): void {
        const hostInput = this.container.querySelector('#device-host') as HTMLInputElement;
        const portInput = this.container.querySelector('#device-port') as HTMLInputElement;

        if (!hostInput.value || !portInput.value) {
            return;
        }

        // Auto-generate device name based on host and timestamp
        const timestamp = new Date().toLocaleString('zh-CN', { 
            year: 'numeric',
            month: '2-digit',
            day: '2-digit',
            hour: '2-digit',
            minute: '2-digit'
        });
        const autoGeneratedName = `设备 ${hostInput.value}:${portInput.value} (${timestamp})`;

        this.connectToDevice({
            name: autoGeneratedName,
            host: hostInput.value,
            port: parseInt(portInput.value, 10)
        });
    }
    




    public getContainer(): HTMLElement {
        return this.container;
    }

    public mount(parent: HTMLElement): void {
        parent.appendChild(this.container);
    }

    public unmount(): void {
        if (this.container.parentElement) {
            this.container.parentElement.removeChild(this.container);
        }
    }

    public handleConnectionResult(success: boolean, message: string): void {
        if (success) {
            this.showSuccessMessage(message);
            // Clear input fields
            const hostInput = this.container.querySelector('#device-host') as HTMLInputElement;
            const portInput = this.container.querySelector('#device-port') as HTMLInputElement;
            if (hostInput) hostInput.value = '';
            if (portInput) portInput.value = '5555';
            
            // Close the panel after a short delay
            setTimeout(() => {
                this.close();
            }, 1500);
        } else {
            // Show error message
            alert(`连接失败: ${message}`);
        }
    }

    private showSuccessMessage(message: string): void {
        const successDiv = document.createElement('div');
        successDiv.className = 'success-message fade-in';
        successDiv.innerHTML = `
            <svg viewBox="0 0 24 24" fill="currentColor" width="20" height="20">
                <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z"/>
            </svg>
            <span>${message}</span>
        `;
        
        // Insert at the top of the panel
        const panel = this.container.querySelector('.quick-connect-panel');
        if (panel && panel.firstElementChild) {
            panel.insertBefore(successDiv, panel.firstElementChild.nextSibling);
        }
        
        // Remove after animation
        setTimeout(() => {
            successDiv.remove();
        }, 3000);
    }
}

// Make QuickConnect available globally for onclick handlers
(window as any).QuickConnect = QuickConnect;